name: deploy-prod
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      image: ghcr.io/${{ github.repository_owner }}/ilegal-platform-web
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/ilegal-platform-web
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=ref,event=tag
      - name: Build & Push apps/web
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./apps/web
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export DOMAIN_DOCS=docs.ilegal.ro
            export WEB_IMAGE=${{ needs.publish.outputs.image }}@${{ needs.publish.outputs.digest }}
            # dacă pachetul GHCR e privat, decomentează:
            # export GHCR_USER=${{ github.repository_owner }}
            # export GHCR_TOKEN=${{ secrets.GHCR_TOKEN }}
            cd ~/ilegal-platform && ./scripts/deploy-prod.sh
